-- GENERATED by `lua theme-manifest.lua dump` - do not hand-edit, re-run to refresh.
return {
  classes = {
    "container",
    "hero",
    "nav-separator",
    "post",
    "section-label",
    "site-footer",
    "site-header",
    "site-nav",
    "wordmark",
    "work-card",
    "work-card-description",
    "work-card-title",
    "work-cover",
    "work-grid",
    "work-section",
    "writing-all-link",
    "writing-date",
    "writing-heading",
    "writing-heading-row",
    "writing-intro",
    "writing-item",
    "writing-list",
    "writing-section",
    "writing-tag",
    "writing-title",
  },
  font_families = {
    "Newsreader",
    "IBM Plex Mono",
    "Georgia",
    "Calibri",
    "Segoe UI",
    "SFMono-Regular",
  },
  fonts = {
    {
      family = "Newsreader",
      file = "newsreader-roman.woff2",
      style = "normal",
      weight = "400 600",
    },
    {
      family = "Newsreader",
      file = "newsreader-italic.woff2",
      style = "italic",
      weight = "400",
    },
    {
      family = "IBM Plex Mono",
      file = "ibm-plex-mono-400.woff2",
      style = "normal",
      weight = "400",
    },
    {
      family = "IBM Plex Mono",
      file = "ibm-plex-mono-500.woff2",
      style = "normal",
      weight = "500",
    },
    {
      family = "IBM Plex Mono",
      file = "ibm-plex-mono-600.woff2",
      style = "normal",
      weight = "600",
    },
  },
  generated_at = "2026-07-22",
  regions = {
    sections = {
      "work",
      "writing",
    },
    tags = {
      "header",
      "nav",
      "footer",
    },
  },
  tokens = {
    {
      name = "--color-bg",
      value = "#040405",
    },
    {
      name = "--color-surface",
      value = "#0c0c0c",
    },
    {
      name = "--color-fg",
      value = "#f2f4f7",
    },
    {
      name = "--color-muted-1",
      value = "#969da3",
    },
    {
      name = "--color-muted-2",
      value = "#868d95",
    },
    {
      name = "--color-muted-3",
      value = "#5f666e",
    },
    {
      name = "--color-muted-4",
      value = "#565c64",
    },
    {
      name = "--color-border",
      value = "#1e1e1e",
    },
    {
      name = "--color-border-soft",
      value = "#171717",
    },
    {
      name = "--color-accent",
      value = "var(--accent, #5CC6E8)",
    },
    {
      name = "--color-accent-project",
      value = "oklch(0.86 0.21 142)",
    },
    {
      name = "--color-accent-date",
      value = "oklch(0.75 0.11 142)",
    },
    {
      name = "--color-selection",
      value = "color-mix(in oklab, var(--color-accent) 30%, transparent)",
    },
    {
      name = "--color-cover-pattern",
      value = "rgba(255, 64, 176, 0.10)",
    },
    {
      name = "--color-separator",
      value = "#2a2a2a",
    },
    {
      name = "--font-serif",
      value = "\"Newsreader\", Georgia, serif",
    },
    {
      name = "--font-sans",
      value = "Calibri, \"Segoe UI\", sans-serif",
    },
    {
      name = "--font-mono",
      value = "\"IBM Plex Mono\", ui-monospace, \"SFMono-Regular\", monospace",
    },
    {
      name = "--content-width",
      value = "748px",
    },
  },
}
